include: package:leancode_lint/analysis_options.yaml

# # Optional lint rules configuration
# custom_lint:
#   rules:
#     - use_design_system_item:
#       AppText:
#         - instead_of: Text
#           from_package: flutter
#         - instead_of: RichText
#           from_package: flutter
#       AppScaffold:
#         - instead_of: Scaffold
#           from_package: flutter

analyzer:
  exclude:
    - '**/*.g.dart'
