name: watchyy
description: "Watchyy app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.3
  hooks_riverpod: ^2.5.1
  http: ^1.2.2
  icons_plus: ^5.0.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  riverpod: ^2.5.1
  sentry_flutter: ^8.3.0
  shared_preferences: ^2.2.3
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  url_launcher: ^6.3.0

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^12.1.0

flutter:
  uses-material-design: true